### ISSUE TITLE
알람을 페이징하고 읽었음 마킹할 수 있게 한다.

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/canoe-web#11]
일주일이면 되겠죠? @parti-xyz/owners

**Comment by rest515** [comment]
일주일 지난 메시지를 삭제하면서.. 미처 못 본 사용자에게 메일로 목록을 보내주면 어떨까요?

**Comment by mozodev** [comment]
일주일 좋은 거 같습니다. 그런데 확실히 보고 싶은 사람도 있을 거 같은데
일주일치만 보여주고 전체 보기 링크를 둬서 볼 수 있게 하면 어떨까요?
메일로 보내기하면 보낸 후 삭제인가요? 복잡해지면 이게 좋을 수도 있겠습니다.

**Comment by dalikim** [comment]
@mozodev 님 커멘트(의 의도는 그게 아닐지 몰라도)를 보니
때가 올때까지 복잡도를 낮추기 위해 알람을 삭제 정책을 보류하는게 좋겠다싶네요.

이 이슈 수정해볼께요.

**Comment by dalikim** [comment]
위의 규칙에서 페이징을 넣고(그건 간단하니까요) 필요가 올때까지 보류하면 어떨까 합니다.

**Comment by dalikim** [comment]
요렇게 바꿔보는건 어떨까요? @parti-xyz/owners

**Comment by dalikim** [comment]
@berry502 알아 보신 바가 있는지요?

**Comment by dalikim** [comment]
@berry502 이슈가 지지부진하게 며칠 질질 끌려서 닫았구요.

http://canoe.parti.dev/app/messages 

<img width="853" alt="2016-01-29 2 05 05" src="https://cloud.githubusercontent.com/assets/1650024/12667608/57873a66-c691-11e5-89cc-dfcd0552c129.png">

이렇게 까지 구현한 것으로 이 이슈를 닫고 필요에 따라 새로운 이슈를 만드는게 좋을 듯합니다.
