### ISSUE TITLE
논의에서 일어나는 일을 타임라인으로 볼 수 있습니다.

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/canoe-web#16]
논의 타임라인을 봅니다.

* 타임라인에 의견을 생성시점 기준으로 배치
* 타임라인에 제안의 CRUD 이벤트 로그 배치 
* 타임라인에 결정 내용 변경 사항 로그 배치

현재 논의 상세 페이지에서 의견 패널을 대치하려 합니다.

**Comment by dalikim** [comment]
투표되는 것도 타임라인에 배치할까요?

**Comment by mozodev** [comment]
네 좋아요!
