### ISSUE TITLE
rails-assets를 계속 가져 가야할지 논의해 봅시다. 

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/canoe-web#18]
참조 rails-assets/rails-assets/issues/291

이런 이야기가 있습니다. 2016년까지는 운영한다고 하나 불안하긴 합니다.

**Comment by rest515** [comment]
다른 대안을 찾는게 좋겠네요. 그런데 말씀하신대로 저도 bower보다 다른 대안이 있으면 좋겠구요. 젬을 이용하는게 좋기는 한데, 젬이 없는 경우도 많아서 고민이 되네요.

**Comment by dalikim** [comment]
만일 옮긴다면 bower말고 대안이 없기는 합니다. go하자면 가겠습니다. @parti-xyz/owners

**Comment by phi4grv** [comment]
제가 문제를 이해하지 못해서 질문을 올려봅니다.

rails-asset 홈페이지에 있는 간단한 설명만 읽고 제가 이해한 바는 다음과 같습니다.
* rails-asset은 자바스크립트 패키지 젬을 만든다.
* rails-asset의 젬은 bower를 이용해서 자바스크립트 패키지를을 다운받아 레일즈에서 사용할 수 있게 한다.

이 경우 rails-asset이 운영을 중단한다면 1에서의 젬을 사용할 수 없게 된다는 의미인가요?

**Comment by dalikim** [comment]
@phi4grv 제가 질문 바로 이해했는지 모르겠습니다만 rails-asset을 통해 가져오던 gem은 못쓰겠죠.

**Comment by dalikim** [comment]
https://parti-xyz.hackpad.com/rails-asset--RXu58CENPzp 핵패드 열렸습니다.

그리고 신규 장난감 프로젝트를 headless로
intro를 browerfiy npm base로 변경하기로 했습니다.

**Comment by phi4grv** [comment]
제가 보기엔 browserify는 자바스크립트 모듈 로더에 가까워서 패키지 관리툴인 bower와는 다른 역할을 하는 것 같습니다.
headless로 변경하는 것은 이 이슈보다 더 큰 범위이고 많은 길이 있을 것 같아요. 
만약 bower를 사용하지 않기 위해서 browserify를 사용한다면 검토해 볼만한 다른 툴이 많이 있습니다.
몇년 지난 애기지만 그 당시엔 browserify는 경우 많이 사용되긴 했지만 비판도 많아서 그 대안툴들이 많이 나왔었거든요.
browserify와 비슷한 용도로 사용될 수 있는 툴을 찾아보니 [RequireJS](http://requirejs.org), [SystemJS](https://github.com/systemjs/systemjs), [es6-module-loader](https://github.com/ModuleLoader/es6-module-loader)등이 보입니다.
그리고 좀 다른 스타일로 리액트랑 친하다는 [webpack](https://webpack.github.io/)이 있구요.
제가 예전에 좋아했던 [curl.js](https://github.com/cujojs/curl)도 있습니다.

**Comment by dalikim** [comment]
네 좋네요. 관련된 내용 핵패드에 올려 주시구요. 신규 장난감 프로젝트와 intro를 진행하면서 좀더 이야기 해보죠. 이 이슈는 "rails-assets를 계속 가져 가야할지 논의"를 여는데 의의가 있기에 여기서 닫겠습니다.
