### ISSUE TITLE
선원은 원하면 스스로 하선할 수 있습니다.

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/canoe-web#21]

**Comment by dalikim** [comment]
카누를 만든 사람은 하선할 수 있는 걸까요? 일단 막을까 싶네요.

**Comment by mozodev** [comment]
권한한 선원이면 모두 동일하지 않나요? 
내부적으로 복잡해지는거면 creator를 누군가에게 넘겨주고 빠져도 좋을 거 같습니다만 
우선순위가 높지 않다면 나중에 해도 될 거 같습니다.

**Comment by dalikim** [comment]
카누로 올렸습니다.

http://canoe.parti.xyz/app/discussions/16

**Comment by dalikim** [comment]
스스로 하선 하는 것까지는 일단 구현하고 선장문제는 카누 보면서 다른 이슈로 빼겠습니다.
