### ISSUE TITLE
에디터를 개선합니다

### ISSUE THREAD

**Issue by rest515** [parti-xyz/canoe-web#31]
바라는 기능은 다음입니다.

* 작성 후에 출력될때 oembed 를 적용합니다
* 이미지 업로드를 할 수 있습니다

**Comment by rest515** [comment]
#26 과 관련이 있네요.

**Comment by dalikim** [comment]
opengraph와 oembed 둘 다를 적절하게 표시하는게 맞겠죠?

**Comment by rest515** [comment]
opengraph를 적절하게 표현하는건 어떤 내용일까요?

**Comment by dalikim** [comment]
<img width="485" alt="2016-01-20 10 38 49" src="https://cloud.githubusercontent.com/assets/1650024/12437543/069af600-bf62-11e5-93b8-8e2a020193a0.png">

opengraph를 통해 긁어온 내용을 이정도 포맷으로 뿌려 주려 했거든요.

**Comment by rest515** [comment]
https://github.com/starfishmod/jquery-oembed-all 이 라이브러리를 쓰려는데요. 여긴 오픈그래프 데이터도 활용한다고 합니다.

**Comment by dalikim** [comment]
네 그런데 위에 제가 캡쳐한 것을 보면 내용이 부실해 보여서요. 좀더 테스트 해볼까요?

**Comment by rest515** [comment]
![image](https://cloud.githubusercontent.com/assets/794973/12437612/a8129f24-bf62-11e5-81b9-f86bbb59dce3.png)

테스트해보니 오픈그래프 데이터를 이 정도로 뿌려주네요.

**Comment by dalikim** [comment]
지금 라이브러리는 oembed가 있으면 opengraph를 무시하는 걸로 보여서 내용이 부실한 건 아닐가 했던거구요. 

그리고 실시간으로 해당 사이트에서 긁어오는 구조로 바꾼다면 https://github.com/parti-xyz/spider-api는 어떻게 되는 걸까요?

**Comment by rest515** [comment]
spider-api는 서버에서 데이터를 이용해서 분석할 용도로 필요할 것 같습니다.

**Comment by dalikim** [comment]
실시간으로 프로바이더 oembed 읽어 뿌려주는 것에 대해 부담감은 없을까요? 프로바이더 서비스퀄리티에 우리가 바로 영향 받는 건 아닌지.

**Comment by rest515** [comment]
클라이언트 자원을 활용하는 거고.. 라이브러리가 로딩에 실패했을 경우엔 링크를 보여주는 방식으로 개발하면 될 것 같습니다. 에디터에서 링크의 내용을 보여주는게 서비스 퀄리티에 직접적인 요소일 것 같진 않은데 어떠세요?

**Comment by dalikim** [comment]
글 작성 시 oembed를 로딩하고 그 내용을 그대로 body안에 저장하는 걸로 생각하고 계신 건지요?

**Comment by rest515** [comment]
작성 후에 출력될때 oembed 를 적용합니다. 자바스크립트를 활용하는 라이브러리를 쓰는 걸 고려 중입니다.

**Comment by dalikim** [comment]
에디터에서 링크의 내용을 보여준다고 하셔서 잠시 오해했습니다.

**Comment by dalikim** [comment]
현재 textarea는 그대로 유지하면서 (즉, 위지위그가 아닌)

* textarea 입력되는 순간 그 값의 링크를 감지하여 oembed미리보기 기능과
* 여러개의 파일을 업로드 할 수 있는 기능

이면 될까요?

**Comment by dalikim** [comment]
oembed jquery plugin이 fallback을 위해 opengraph를 차용할 때 yql 즉 야후API를 쓰는데요.
대략 알아본 바로는 검색이 막힌 사이트는 야후에서 데이터를 긁지 않아 API가 작동하지 않네요.
(우리나라 포털들) 작은 문제지만 야후API 라이센스도 궁금하구요.

좀더 살펴볼텐데 의견 있으면 주세요.

**Comment by dalikim** [comment]
opengraph는 필요할 때 이슈를 다시 만들겠습니다. 지금은 필요없어 보이구요. 만일 필요하다면  https://github.com/parti-xyz/spider-api 를 이용할까 합니다.
