### ISSUE TITLE
헤더 정리

### ISSUE THREAD

**Issue by rest515** [parti-xyz/canoe-web#35]
* 전체(드랍다운) - 카누/논의/사용자
* 개인 - 최근논의/읽지않은논의/내가탑승한카누

**Comment by rest515** [comment]
1차로 작업하였네요. 좀 더 열어놓다가 더 이상 작업이 없으면 이 이슈는 닫겠습니다.

**Comment by dalikim** [comment]
2차로 작업하였고 별 이견 없어서 닫습니다. 당분간 써보고 다시 생기는 개선 사항은 새로운 이슈로 열어 봅시다.
