### ISSUE TITLE
논의 상세 페이지 레이아웃 변경

### ISSUE THREAD

**Issue by rest515** [parti-xyz/canoe-web#38]

**Comment by dalikim** [comment]
요건 뭐가 더 남았을까요?

**Comment by dalikim** [comment]
이 이슈 닫고 필요에 따라 좀 더 세분화 하면 어떨까요? @parti-xyz/owners

**Comment by dalikim** [comment]
@rest515 타임라인에 액티비티라든가 다듬을게 있으실거 같은데 작은 이슈로 나눠서 올려 보면 합니다.
