### ISSUE TITLE
해당 카누 모든 선원들에게 간단하게 멘션을 줍니다.

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/canoe-web#42]

**Comment by dalikim** [comment]
예를 들어 @crew 하면 모든 선원들에게 알람이 가게 하면 어떨까 싶습니다. @all 이나?

**Comment by mozodev** [comment]
:+1: all이 직관적이지만 카누 스타일에는 crew가 좋겠습니다.

딴 이야기이지만 깃헙도 노티가 가니까요... ㅋㅋㅋㅋ
여긴 단체라서 노티가 안간거 같지만 https://github.com/crew
이 사람은 사용자라 아마 노티가 갈 수도 있겠네요 ㅎㅎ https://github.com/all
사용하지 않는 거 같긴하지만요 ㅎㅎㅎ

**Comment by dalikim** [comment]
그런 경우엔 보통 가입 시 nick을 막지요.

카누 slug을 정할 때도 app/admin 등을 막고 있거든요. 

https://github.com/parti-xyz/canoe-web/commit/1d8b473f151af42acc4b1a75ad968ced53808ae8#diff-f89fb6215e4d76a0a9c953eddcc207d6R11

다른 분들도 이 @crew에 동의한다면 SSO 이슈도 따라가야합니다.
생각해보니 SSO에 nick 중에 예상 가능하게 우리가 쓸 것은 미리 막아놔야겠네요.
