### ISSUE TITLE
SEO를 위해 메타태그를 답니다.

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/canoe-web#45]
* 나머지 페이지
  site:        'canoe.parti.xyz',
  description: '카누는 "일상 민주주의"와 "민주적인 조직 구조"를 실현하려는 그룹을 위한 서비스입니다.',
  keywords:    '일상민주주의, democracy, 의사결정',
  separator:   "&mdash;".html_safe,

  og:
  type:     'website'
  url:      root_url
  image:    default image

* 카누
  title:       '카누제목',
  description: '카누설명',

  og:
  image:       카누 커버 || 카누 로고
  url:         카누 perma url

* 논의
  title:       '논의제목',
  description: '논의설명',

  og:
  image:       결정사항에 있는 첫번째 이미지
  url:         논의 url ex) 다음엔 http://canoe.parti.xyz/better-canoe/4

**Comment by dalikim** [comment]
"일단 구글봇, 페이스북이나 트위터 등에서 링크를 공유할 때 적절한 메타 데이터를 줍시다!"라고 @mozodev 님이 핵패드에 쓰신 걸 커멘트로 남겨둡니다.

**Comment by berry502** [comment]
http://hackfoldr.org/parti-xyz/https%253A%252F%252Fparti-xyz.hackpad.com%252F--u8DEcMMyzXD
