### ISSUE TITLE
회원가입 별명 -> 아이디로 

### ISSUE THREAD

**Issue by berry502** [parti-xyz/canoe-web#47]
별명이라고 되어 있어서 한글로 쓰는 경우가 많았어요.

**Comment by dalikim** [comment]
회원가입은 parti-xyz/parti-sso 프로젝트라 그 아래 이슈로 옮기는게 편할 듯 합니다.
(회원가입 url은 canoe.parti.xyz가 아닌 sso.parti.xyz이죠?)
아 근데 옮기려보고 보니 parti-xyz/parti-sso#8 이슈가 있네요. 이 이슈는 거기에 링크 걸고 닫도록 하겠습니다.
