### ISSUE TITLE
제안에 대한 의견을 적고 싶습니다.

### ISSUE THREAD

**Issue by mozodev** [parti-xyz/canoe-web#48]
의견에 있는 호응하기처럼 제안에도 의견 적기 이런 링크를 만들어서 클릭하면
1번 제안이 참조된 상태로 의견을 적을 수 있으면 어떨까요?

아 복잡한 거 같은데... 그냥 1번 제안이 이런 뜻인가요? 이렇게 적어도 되겠네요..
의견에 제안 참조라는 지표가 갖는 의미나 효용이 있을까요? 많이 언급된 제안이라는 지표가 될 수 있겠네요...
음 특별한 무언가 있는지는 잘 모르겠습니다.

**Comment by dalikim** [comment]
의견에 제안1 이렇게 적으면 해당 제안에 대해 툴팁이 보이고 링크도 걸립니다. 

현잰 요까지만 구현되어 있구요.

말씀하신 내용은 젠가에서 테스트 했던 기능인데 복잡도 때문에 미뤄두던건데 잘 꺼내주셨네요 

아참 이런 논의는 카누가 어울릴 수도 있겠네요.

**Comment by dalikim** [comment]
카누에서 이야기 해보는 건 어떨가요? 요건 닫겠습니다.
