### ISSUE TITLE
iframe 작업관련 

### ISSUE THREAD

**Issue by YU-YOU** [parti-xyz/canoe-web#50]
카누를 카누페이지가 아닌 페이지에서 사용하고 싶습니다. 
iframe에서 사용하고 싶은데, 
 x-frame-option = SAMEORIGIN 으로 되어있어서, 

Refused to display 'http://canoe.parti.xyz/wagl' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'

로 뜹니다. 

확인부탁드립니다.

**Comment by mozodev** [comment]
궁금해서 그러는데요 혹시 초기 화면이나 목록 화면 이런데서 사용하시는 카누 내용을 보고 싶으신건가요?
어떤 식으로든 필요한 데이터를 사용할 수 있게 해드리는 게 좋을 거 같은데요... 깃헙 api 처럼? ㅎㅎ

**Comment by mozodev** [comment]
done!
