### ISSUE TITLE
로그인하고 첫 페이지에 보여 줄 의논이 없을 경우를 처리합니다. 

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/canoe-web#55]
최근에 논의가 진행 중인 카누를 몇 개 보여 줍니다. 승선요청 가능한 카누만 보여주는게 맞겠죠?

**Comment by mozodev** [comment]
넵 public cano / limit 2? desc?

**Comment by dalikim** [comment]
다른 카누에서 진행 중인 논의와 승선할 카누 검색 기능을 넣어 줍니다.
