### ISSUE TITLE
푸쉬 관련 앱 등록

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/canoe-web#84]
개발자 등록 등등

**Comment by dalikim** [comment]
개발자 계정 등록 도움을 바랍니다. @rest515

**Comment by dalikim** [comment]
키튼님께서 "안드로이드 푸시 붙이는 작업이 지체되고 있어서 디자인 QA 2차 수정요청 작업 반영했습니다 안드로이드 작업이 금방 해결이 안되고 있으니 로그인 연동이나 애플 푸시쪽이 준비되면 먼저 작업하는 것도 좋을것 같습니다"라는데요

애플 진행 상황이 궁금합니다. @rest515

**Comment by dalikim** [comment]
애플 진행 상황이 궁금합니다. @rest515

**Comment by rest515** [comment]
네네 다시 신청해야 하는데 아직 못했네요. 오늘 진행하겠습니다.

**Comment by rest515** [comment]
개인계정으로 등록했습니다. 볼트에 등록해 두었습니다.

**Comment by dalikim** [comment]
키튼에게 전달했습니다. 종료합니다.
