### ISSUE TITLE
한글 깨지는 문제 디버깅

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/canoe-web#89]

**Comment by KeatonY** [comment]
"User-Agent", "Canoe App v(버전정보)"

앱에서는 User-Agent 에 카누앱이라고 적어서 보내고 있습니다.

**Comment by dalikim** [comment]
일정 점검 미팅 결과 우선 순위에 의해 미뤄두기로 하였습니다. 백로그에 다시 넣어 둘께요.
